// <auto-generated />
using System;
using EmployeeManagementCoreApp.Helper.Database;
using EmployeeManagementCoreApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
namespace EmployeeManagementCoreApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200326154351_RemoveExtraEmployeeClass")]
    partial class RemoveExtraEmployeeClass
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
            modelBuilder.Entity("EmployeeManagementCoreApp.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(15);
                    b.Property<string>("Description");
                    b.Property<byte[]>("Picture");
                    b.HasKey("CategoryID");
                    b.ToTable("Category");
                });
            modelBuilder.Entity("EmployeeManagementCoreApp.Models.Customer", b =>
                {
                    b.Property<string>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5);
                    b.Property<string>("Address")
                        .HasMaxLength(60);
                    b.Property<string>("City")
                        .HasMaxLength(15);
                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(40);
                    b.Property<string>("ContactName")
                        .HasMaxLength(30);
                    b.Property<string>("ContactTitle")
                        .HasMaxLength(30);
                    b.Property<string>("Country")
                        .HasMaxLength(15);
                    b.Property<string>("Fax")
                        .HasMaxLength(24);
                    b.Property<string>("Phone")
                        .HasMaxLength(24);
                    b.Property<string>("PostalCode")
                        .HasMaxLength(10);
                    b.Property<string>("Region")
                        .HasMaxLength(15);
                    b.HasKey("CustomerID");
                    b.ToTable("Customer");
                });
            modelBuilder.Entity("EmployeeManagementCoreApp.Models.CustomerCustomerDemo", b =>
                {
                    b.Property<string>("CustomerID")
                        .HasMaxLength(5);
                    b.Property<string>("CustomerTypeID")
                        .HasMaxLength(10);
                    b.HasKey("CustomerID", "CustomerTypeID");
                    b.ToTable("CustomerCustomerDemo");
                });
            modelBuilder.Entity("EmployeeManagementCoreApp.Models.CustomerDemographic", b =>
                {
                    b.Property<string>("CustomerTypeID")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10);
                    b.Property<string>("CustomerDesc");
                    b.HasKey("CustomerTypeID");
                    b.ToTable("CustomerDemographic");
                });
            modelBuilder.Entity("EmployeeManagementCoreApp.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
                    b.Property<string>("Address")
                        .HasMaxLength(60);
                    b.Property<DateTime?>("BirthDate");
                    b.Property<string>("City")
                        .HasMaxLength(15);
                    b.Property<string>("Country")
                        .HasMaxLength(15);
                    b.Property<int?>("Department");
                    b.Property<string>("Email")
                        .IsRequired();
                    b.Property<string>("Extension")
                        .HasMaxLength(4);
                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(10);
                    b.Property<DateTime?>("HireDate");
                    b.Property<string>("HomePhone")
                        .HasMaxLength(24);
                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20);
                    b.Property<string>("Name")
                        .HasMaxLength(50);
                    b.Property<string>("Notes");
                    b.Property<byte[]>("Photo");
                    b.Property<string>("PhotoPath")
                        .HasMaxLength(255);
                    b.Property<string>("PostalCode")
                        .HasMaxLength(10);
                    b.Property<string>("Region")
                        .HasMaxLength(15);
                    b.Property<int?>("ReportsTo");
                    b.Property<string>("Title")
                        .HasMaxLength(30);
                    b.Property<string>("TitleOfCourtesy")
                        .HasMaxLength(25);
                    b.HasKey("EmployeeID");
                    b.ToTable("Employee");
                    b.HasData(
                        new
                        {
                            EmployeeID = 1,
                            Department = 2,
                            Email = "mary@gmail.com",
                            FirstName = "Mary",
                            LastName = "Magdalene",
                            Name = "Mary Magdalene"
                        },
                        new
                        {
                            EmployeeID = 2,
                            Department = 0,
                            Email = "jhon@gmail.com",
                            FirstName = "Jhon",
                            LastName = "Hopkins",
                            Name = "Jhon Hopkins"
                        });
                });
            modelBuilder.Entity("EmployeeManagementCoreApp.Models.EmployeeTerritory", b =>
                {
                    b.Property<int>("EmployeeID");
                    b.Property<string>("TerritoryID")
                        .HasMaxLength(20);
                    b.HasKey("EmployeeID", "TerritoryID");
                    b.ToTable("EmployeeTerritory");
                });
            modelBuilder.Entity("EmployeeManagementCoreApp.Models.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
                    b.Property<string>("CustomerID");
                    b.Property<int>("EmployeeID");
                    b.Property<decimal>("Freight")
                        .HasColumnType("decimal(18,4)");
                    b.Property<DateTime>("OrderDate");
                    b.Property<DateTime>("RequiredDate");
                    b.Property<string>("ShipAddress")
                        .HasMaxLength(60);
                    b.Property<string>("ShipCity")
                        .HasMaxLength(15);
                    b.Property<string>("ShipCountry")
                        .HasMaxLength(15);
                    b.Property<string>("ShipName")
                        .HasMaxLength(40);
                    b.Property<string>("ShipPostalCode")
                        .HasMaxLength(10);
                    b.Property<string>("ShipRegion")
                        .HasMaxLength(15);
                    b.Property<int>("ShipVia");
                    b.Property<DateTime>("ShippedDate");
                    b.HasKey("OrderID");
                    b.ToTable("Order");
                });
            modelBuilder.Entity("EmployeeManagementCoreApp.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderID");
                    b.Property<int>("ProductID");
                    b.Property<float>("Discount");
                    b.Property<short>("Quantity");
                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,4)");
                    b.HasKey("OrderID", "ProductID");
                    b.ToTable("OrderDetail");
                });
            modelBuilder.Entity("EmployeeManagementCoreApp.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
                    b.Property<int>("CategoryID");
                    b.Property<bool>("Discontinued");
                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(40);
                    b.Property<string>("QuantityPerUnit")
                        .HasMaxLength(20);
                    b.Property<short>("ReorderLevel");
                    b.Property<int>("SupplierID");
                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,4)");
                    b.Property<short>("UnitsInStock");
                    b.Property<short>("UnitsOnOrder");
                    b.HasKey("ProductID");
                    b.ToTable("Product");
                });
            modelBuilder.Entity("EmployeeManagementCoreApp.Models.Region", b =>
                {
                    b.Property<int>("RegionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
                    b.Property<string>("RegionDescription")
                        .IsRequired()
                        .HasMaxLength(5);
                    b.HasKey("RegionId");
                    b.ToTable("Region");
                });
            modelBuilder.Entity("EmployeeManagementCoreApp.Models.Shipper", b =>
                {
                    b.Property<int>("ShipperID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(40);
                    b.Property<string>("Phone")
                        .HasMaxLength(24);
                    b.HasKey("ShipperID");
                    b.ToTable("Shipper");
                });
            modelBuilder.Entity("EmployeeManagementCoreApp.Models.Supplier", b =>
                {
                    b.Property<int>("SupplierID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
                    b.Property<string>("Address")
                        .HasMaxLength(30);
                    b.Property<string>("City")
                        .HasMaxLength(60);
                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(40);
                    b.Property<string>("ContactName")
                        .HasMaxLength(40);
                    b.Property<string>("ContactTitle")
                        .HasMaxLength(30);
                    b.Property<string>("Country")
                        .HasMaxLength(10);
                    b.Property<string>("Fax")
                        .HasMaxLength(24);
                    b.Property<string>("HomePage")
                        .HasMaxLength(24);
                    b.Property<string>("Phone")
                        .HasMaxLength(15);
                    b.Property<string>("PostalCode")
                        .HasMaxLength(15);
                    b.Property<string>("Region")
                        .HasMaxLength(15);
                    b.HasKey("SupplierID");
                    b.ToTable("Supplier");
                });
            modelBuilder.Entity("EmployeeManagementCoreApp.Models.Territory", b =>
                {
                    b.Property<string>("TerritoryID")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20);
                    b.Property<int>("RegionID");
                    b.Property<string>("TerrritoryDescription")
                        .IsRequired()
                        .HasMaxLength(5);
                    b.HasKey("TerritoryID");
                    b.ToTable("Territory");
                });
#pragma warning restore 612, 618
        }
    }
}
